### ISSUE TITLE
brownie test no test ran in 0.01s

### ISSUE THREAD

**Issue by DarrenWayn** [PatrickAlphaC/brownie_fund_me#19]
![image](https://user-images.githubusercontent.com/22322944/148493912-04ba1edc-e0a5-4892-afb2-be087f93d011.png)
i run brownie test for tests folder but no tests ran in 0.01s, anybody know what is the problem?

**Comment by Dcamy** [comment]
Hi @DarrenWayn, just wondering what happens when you run the other two commands?

`brownie test` should return 2 passed,

`brownie test -k test_only_owner_can_withdraw --network rinkeby` should return 1 skipped, 1 deselected

and

`brownie test -k test_only_owner_can_withdraw --network development` should return 1 passed, 1 deselected

Also noticed on line 4  from brownie import network - network is white, while green for me and the video... maybe something to look into 🤷‍♂️ 

![image](https://user-images.githubusercontent.com/96091379/148762674-a13c5d2f-bfec-4e30-82a7-0fae0063466f.png)

**Comment by PatrickAlphaC** [comment]
For some reason, your tests are in a `__pycache__` folder. 

Can you delete your tests folder, make a new one, and put the tests in there?
